# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b4a891e3c0c6eefb2f544845813e5c3145175e123dcc768c778016dc4bff0b9404d20ad004cdf7c92669ce75bbdb8aa58a7b507e533d446e9628ea2aa4282c2

test:
  secret_key_base: 9785bb375a62693cd410cef7b5a7cf278a26aac0c4f384698589aefac5cc3b70a30c5331f5e4e2441ff5f99dec4a5d6c10b51faacda562a6bc11816daaf4d0f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
